auth_enabled: false  # Disable auth for simplicity (not recommended for production)

server:
  http_listen_port: 3100  # Loki HTTP API port

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # In-memory ring store (single instance setup)
      replication_factor: 1  # No replication (single instance)
  chunk_idle_period: 3m  # Time after which idle chunks are flushed
  max_chunk_age: 1h  # Max chunk lifetime before forced flush
  chunk_retain_period: 30s  # Retain chunks after flush for queries
  wal:
    enabled: true  # Enable Write Ahead Log for durability
    dir: /tmp/wal  # WAL directory (ensure writable)

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper  # Use boltdb-shipper index type
      object_store: filesystem  # Store chunks locally on filesystem
      schema: v11  # Schema version, must match limits_config settings
      index:
        prefix: index_  # Prefix for index files
        period: 24h  # Index file rotation period

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index  # Index storage directory
    cache_location: /tmp/loki/boltdb-cache  # BoltDB cache location
  filesystem:
    directory: /tmp/loki/chunks  # Chunk storage directory

limits_config:
  reject_old_samples: true  # Reject samples older than max age
  reject_old_samples_max_age: 168h  # Max age for samples to accept (7 days)
  allow_structured_metadata: false  # Disable structured metadata for v11 schema

compactor:
  working_directory: /tmp/loki/compactor  # Must be writable dir to avoid permission errors

table_manager:
  retention_deletes_enabled: true  # Enable retention-based deletes
  retention_period: 168h  # Retention period for data (7 days)
