receivers:
  # OTLP receiver for gRPC and HTTP (Traces, Metrics, Logs)
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Prometheus receiver to scrape metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['0.0.0.0:8888']  # Collector's own metrics
        - job_name: 'tempo'
          static_configs:
            - targets: ['tempo:3200']
        - job_name: 'grafana'
          static_configs:
            - targets: ['grafana:3000']

exporters:
  # Export traces to Tempo
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

  # Export metrics for Prometheus to scrape
  prometheus:
    endpoint: "0.0.0.0:14317"

  # Export logs to Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "otel-collector"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]

    metrics:
      receivers: [prometheus]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [loki]

